#!/bin/bash

# Claude Flow - One-Click Setup Script
# 5분 만에 설치하고 시작하세요!

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Banner
echo -e "${CYAN}"
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                                ║"
echo "║   ██████╗██╗      █████╗ ██╗   ██╗██████╗ ███████╗            ║"
echo "║  ██╔════╝██║     ██╔══██╗██║   ██║██╔══██╗██╔════╝            ║"
echo "║  ██║     ██║     ███████║██║   ██║██║  ██║█████╗              ║"
echo "║  ██║     ██║     ██╔══██║██║   ██║██║  ██║██╔══╝              ║"
echo "║  ╚██████╗███████╗██║  ██║╚██████╔╝██████╔╝███████╗            ║"
echo "║   ╚═════╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═════╝ ╚══════╝            ║"
echo "║                        FLOW                                    ║"
echo "║                                                                ║"
echo "║        엔터프라이즈급 AI 에이전트 오케스트레이션 플랫폼        ║"
echo "║                                                                ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check prerequisites
check_prerequisites() {
    echo -e "${BLUE}[1/5] 사전 요구사항 확인 중...${NC}"

    # Docker
    if ! command -v docker &> /dev/null; then
        echo -e "${RED}✗ Docker가 설치되어 있지 않습니다.${NC}"
        echo "  https://docs.docker.com/get-docker/ 에서 설치해주세요."
        exit 1
    fi
    echo -e "${GREEN}✓ Docker 설치됨${NC}"

    # Docker Compose
    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        echo -e "${RED}✗ Docker Compose가 설치되어 있지 않습니다.${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Docker Compose 설치됨${NC}"

    # Claude CLI (optional)
    if command -v claude &> /dev/null; then
        echo -e "${GREEN}✓ Claude CLI 설치됨${NC}"
    else
        echo -e "${YELLOW}! Claude CLI 미설치 (나중에 설치 가능)${NC}"
    fi
}

# Interactive configuration
configure_environment() {
    echo ""
    echo -e "${BLUE}[2/5] 환경 설정${NC}"

    ENV_FILE="docker-compose/.env"

    # Create .env from template if not exists
    if [ ! -f "$ENV_FILE" ]; then
        cp docker-compose/.env.example "$ENV_FILE" 2>/dev/null || cat > "$ENV_FILE" << 'EOF'
# Claude Flow Configuration
# Generated by setup.sh

# Slack Configuration (Required)
SLACK_APP_TOKEN=
SLACK_BOT_TOKEN=
SLACK_SIGNING_SECRET=

# GitLab Configuration (Optional)
GITLAB_URL=
GITLAB_GROUP=
GITLAB_TOKEN=

# n8n Configuration
N8N_USER=admin@local.dev
N8N_PASSWORD=Localdev123

# Claude Configuration
CLAUDE_MODEL=claude-sonnet-4-20250514
CLAUDE_TIMEOUT_SECONDS=600
EOF
    fi

    echo ""
    echo -e "${YELLOW}Slack 앱 설정이 필요합니다.${NC}"
    echo "1. https://api.slack.com/apps 에서 새 앱 생성"
    echo "2. Socket Mode 활성화 → App Token 생성 (xapp-xxx)"
    echo "3. Event Subscriptions → app_mention, message.channels, reaction_added"
    echo "4. OAuth & Permissions → Bot Token 복사 (xoxb-xxx)"
    echo ""

    read -p "Slack App Token (xapp-xxx): " SLACK_APP_TOKEN
    read -p "Slack Bot Token (xoxb-xxx): " SLACK_BOT_TOKEN
    read -p "Slack Signing Secret: " SLACK_SIGNING_SECRET

    # Update .env file
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sed -i '' "s|^SLACK_APP_TOKEN=.*|SLACK_APP_TOKEN=$SLACK_APP_TOKEN|" "$ENV_FILE"
        sed -i '' "s|^SLACK_BOT_TOKEN=.*|SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN|" "$ENV_FILE"
        sed -i '' "s|^SLACK_SIGNING_SECRET=.*|SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET|" "$ENV_FILE"
    else
        sed -i "s|^SLACK_APP_TOKEN=.*|SLACK_APP_TOKEN=$SLACK_APP_TOKEN|" "$ENV_FILE"
        sed -i "s|^SLACK_BOT_TOKEN=.*|SLACK_BOT_TOKEN=$SLACK_BOT_TOKEN|" "$ENV_FILE"
        sed -i "s|^SLACK_SIGNING_SECRET=.*|SLACK_SIGNING_SECRET=$SLACK_SIGNING_SECRET|" "$ENV_FILE"
    fi

    echo -e "${GREEN}✓ 환경 설정 완료${NC}"

    # Optional: GitLab
    echo ""
    read -p "GitLab MR 리뷰 기능을 사용하시겠습니까? (y/N): " use_gitlab
    if [[ "$use_gitlab" =~ ^[Yy]$ ]]; then
        read -p "GitLab URL (예: https://gitlab.example.com): " GITLAB_URL
        read -p "GitLab Group (예: my-org/my-group): " GITLAB_GROUP
        read -p "GitLab Token (glpat-xxx): " GITLAB_TOKEN

        if [[ "$OSTYPE" == "darwin"* ]]; then
            sed -i '' "s|^GITLAB_URL=.*|GITLAB_URL=$GITLAB_URL|" "$ENV_FILE"
            sed -i '' "s|^GITLAB_GROUP=.*|GITLAB_GROUP=$GITLAB_GROUP|" "$ENV_FILE"
            sed -i '' "s|^GITLAB_TOKEN=.*|GITLAB_TOKEN=$GITLAB_TOKEN|" "$ENV_FILE"
        else
            sed -i "s|^GITLAB_URL=.*|GITLAB_URL=$GITLAB_URL|" "$ENV_FILE"
            sed -i "s|^GITLAB_GROUP=.*|GITLAB_GROUP=$GITLAB_GROUP|" "$ENV_FILE"
            sed -i "s|^GITLAB_TOKEN=.*|GITLAB_TOKEN=$GITLAB_TOKEN|" "$ENV_FILE"
        fi
        echo -e "${GREEN}✓ GitLab 설정 완료${NC}"
    fi
}

# Build and start services
start_services() {
    echo ""
    echo -e "${BLUE}[3/5] 서비스 시작 중...${NC}"

    cd docker-compose

    # Build
    echo "Docker 이미지 빌드 중... (최초 실행 시 수 분 소요)"
    docker-compose build --quiet

    # Start
    docker-compose up -d

    echo -e "${GREEN}✓ 서비스 시작됨${NC}"
    cd ..
}

# Health check
health_check() {
    echo ""
    echo -e "${BLUE}[4/5] 헬스 체크 중...${NC}"

    MAX_RETRIES=30
    RETRY_COUNT=0

    while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
        if curl -s http://localhost:8080/api/v1/health > /dev/null 2>&1; then
            echo -e "${GREEN}✓ Claude Flow API 정상${NC}"
            break
        fi
        RETRY_COUNT=$((RETRY_COUNT + 1))
        echo "  대기 중... ($RETRY_COUNT/$MAX_RETRIES)"
        sleep 2
    done

    if [ $RETRY_COUNT -eq $MAX_RETRIES ]; then
        echo -e "${YELLOW}! API 응답 대기 시간 초과 (나중에 확인 필요)${NC}"
    fi

    # Check n8n
    if curl -s http://localhost:5678 > /dev/null 2>&1; then
        echo -e "${GREEN}✓ n8n 워크플로우 엔진 정상${NC}"
    else
        echo -e "${YELLOW}! n8n 시작 중... (수 분 소요될 수 있음)${NC}"
    fi
}

# Final summary
show_summary() {
    echo ""
    echo -e "${BLUE}[5/5] 설치 완료!${NC}"
    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║                    Claude Flow 설치 완료!                     ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${CYAN}서비스 URL:${NC}"
    echo "  • API:        http://localhost:8080"
    echo "  • Dashboard:  http://localhost:5173  (별도 실행 필요)"
    echo "  • n8n:        http://localhost:5678  (admin@local.dev / Localdev123)"
    echo ""
    echo -e "${CYAN}Slack에서 테스트:${NC}"
    echo "  @claude-flow 안녕하세요!"
    echo ""
    echo -e "${CYAN}다음 단계:${NC}"
    echo "  1. Claude CLI 인증: ${YELLOW}claude login${NC}"
    echo "  2. n8n 워크플로우 활성화: http://localhost:5678"
    echo "  3. 대시보드 실행: ${YELLOW}cd dashboard && npm install && npm run dev${NC}"
    echo ""
    echo -e "${CYAN}문서:${NC}"
    echo "  https://github.com/your-org/claude-flow"
    echo ""
    echo -e "${YELLOW}문제가 있으면:${NC}"
    echo "  docker-compose logs -f  # 로그 확인"
    echo "  ./setup.sh --reset      # 초기화 후 재설치"
    echo ""
}

# Reset function
reset_installation() {
    echo -e "${YELLOW}설치 초기화 중...${NC}"
    cd docker-compose
    docker-compose down -v 2>/dev/null || true
    rm -f .env
    cd ..
    echo -e "${GREEN}✓ 초기화 완료. ./setup.sh 로 재설치하세요.${NC}"
    exit 0
}

# Main
main() {
    # Handle arguments
    if [ "$1" == "--reset" ]; then
        reset_installation
    fi

    if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
        echo "Usage: ./setup.sh [OPTIONS]"
        echo ""
        echo "Options:"
        echo "  --reset    기존 설치 초기화"
        echo "  --help     도움말 표시"
        exit 0
    fi

    check_prerequisites
    configure_environment
    start_services
    health_check
    show_summary
}

main "$@"
